package care.smith.top.top_phenotypic_query.h2;

public class PKField extends Field {

  public PKField(String name) {
    super(name, "bigint");
    notNull = true;
    props = "GENERATED BY DEFAULT AS IDENTITY";
  }

  public Value value(int val) {
    return new Value(val);
  }
}
