CREATE TABLE subject (
    subject_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    birth_date timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sex        text   NOT NULL,
    PRIMARY KEY (subject_id)
);

CREATE TABLE assessment1 (
    assessment_id bigint                   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    subject_id    bigint                   NOT NULL REFERENCES subject,
    created_at    timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    crea        numeric,
    PRIMARY KEY (assessment_id)
);

INSERT INTO subject VALUES
    (1, '2002-01-01', 'female'),
    (2, '1982-01-01', 'female'),
    (3, '2002-01-01', 'male'),
    (4, '1982-01-01', 'male'),
    (5, '2002-01-01', 'female');

INSERT INTO assessment1 (subject_id, created_at, crea) VALUES
    (1, '2023-03-12T12:43:00', 180),
    (1, '2023-03-11T12:43:00', 100),
    (1, '2023-03-10T12:43:00', 90),
    (2, '2023-03-12T12:43:00', 180),
    (2, '2023-01-02T12:43:00', 110),
    (2, '2023-01-03T12:43:00', 65),
    (2, '2023-01-04T12:43:00', 55),
    (2, '2023-01-05T12:43:00', 50),
    (3, '2023-03-12T12:43:00', 180),
    (3, '2020-01-02T12:43:00', 110),
    (3, '2020-01-03T12:43:00', 105),
    (4, '2023-03-12T12:43:00', 190),
    (4, '2023-01-02T12:43:00', 170),
    (4, '2023-01-03T12:43:00', 160),
    (5, '2023-03-12T12:43:00', 180),
    (5, '2023-03-11T12:43:00', 100),
    (5, '2023-03-10T12:43:00', 90),
    (5, '2023-01-02T12:43:00', 110),
    (5, '2023-01-03T12:43:00', 65),
    (5, '2023-01-04T12:43:00', 55),
    (5, '2023-01-05T12:43:00', 50);
