CREATE TABLE subject (
    subject_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    birth_date date   NOT NULL,
    sex        text   NOT NULL,
    PRIMARY KEY (subject_id)
);

CREATE TABLE assessment1 (
    assessment_id bigint                   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    subject_id    bigint                   NOT NULL REFERENCES subject,
    created_at    timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    height        numeric,
    weight        numeric,
    PRIMARY KEY (assessment_id)
);

INSERT INTO subject VALUES
    (1, current_date - '55' year, 'female'),
    (2, current_date - '55' year, 'male'),
    (3, current_date - '55' year, 'male');

INSERT INTO assessment1 (subject_id, created_at, height, weight) VALUES
    (1, '2000-05-20T12:43:00', 170, 70),
    (2, '2000-12-01T06:35:00', 205, 90),
    (3, '2000-01-01T01:00:00', NULL, 75);
