CREATE TABLE assessment1 (
    assessment_id bigint                   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    subject_id    bigint                   NOT NULL,
    created_at    timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    weight        numeric,
    PRIMARY KEY (assessment_id)
);

INSERT INTO assessment1 (subject_id, created_at, weight) VALUES
    (1, '2000-05-20T12:43:00', 170),
    (1, '1995-05-20T12:43:00', 70),
    (2, '2000-12-01T06:35:00', 90),
    (2, '2001-12-01T06:35:00', 190),
    (2, '2002-12-01T06:35:00', 190),
    (2, '2003-12-01T06:35:00', 190),
    (3, '1999-01-01T01:00:00', 165),
    (3, '2000-01-01T01:00:00', 175),
    (3, '1950-01-01T01:00:00', 75),
    (5, '1999-01-01T01:00:00', 165),
    (5, '2000-01-01T01:00:00', 175),
    (4, '2000-01-01T01:00:00', 75);
