CREATE TABLE subject (
    subject_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    birth_date timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sex        text   NOT NULL,
    PRIMARY KEY (subject_id)
);

CREATE TABLE assessment1 (
    assessment_id bigint                   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    subject_id    bigint                   NOT NULL REFERENCES subject,
    created_at    timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    height        numeric,
    weight        numeric,
    PRIMARY KEY (assessment_id)
);

INSERT INTO subject VALUES
    (1, '2002-01-01', 'female'),
    (2, '1982-01-01', 'female'),
    (3, '2002-01-01', 'male'),
    (4, '1982-01-01', 'male'),
    (5, '2002-01-01', 'female');

INSERT INTO assessment1 (subject_id, created_at, height, weight) VALUES
    (1, '2000-05-20T12:43:00', 170, null),
    (2, '2000-12-01T06:35:00', null, 95),
    (3, '2000-05-20T12:43:00', null, null),
    (4, '2000-12-01T06:35:00', null, 85),
    (5, '2000-05-20T12:43:00', 150, 75);
