name: Deploy JavaDoc

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy JavaDoc
        uses: MathieuSoysal/Javadoc-publisher.yml@v3.0.2
        env:
          GH_MAVEN_PKG_AUTH_TOKEN: ${{ secrets.GH_MAVEN_PKG_AUTH_TOKEN }}
          GH_MAVEN_PKG_USER: ${{ secrets.GH_MAVEN_PKG_USER }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-version: 17
          project: maven
          custom-command: mvn -B javadoc:aggregate --no-transfer-progress -s .mvn-ci.xml --file pom.xml
