name: Publish snapshot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_MAVEN_PKG_AUTH_TOKEN: ${{ secrets.GH_MAVEN_PKG_AUTH_TOKEN }}
      GH_MAVEN_PKG_USER: ${{ secrets.GH_MAVEN_PKG_USER }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - run: mvn -B install -DskipTests --no-transfer-progress -s .mvn-ci.xml --file pom.xml

  publish-snapshot:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      GH_MAVEN_PKG_AUTH_TOKEN: ${{ secrets.GH_MAVEN_PKG_AUTH_TOKEN }}
      GH_MAVEN_PKG_USER: ${{ secrets.GH_MAVEN_PKG_USER }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Get version
      run: echo project_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_ENV

    - name: Append "-SNAPSHOT" to projects version
      if: ${{ !endsWith(env.project_version, 'SNAPSHOT') }}
      run: mvn versions:set "-DnewVersion=${{ env.project_version }}-SNAPSHOT"
    
    - name: Build with Maven
      run: mvn -B package -DskipTests -s .mvn-ci.xml --file pom.xml
      env:
        GH_MAVEN_PKG_AUTH_TOKEN: ${{ secrets.GH_MAVEN_PKG_AUTH_TOKEN }}
        GH_MAVEN_PKG_USER: ${{ secrets.GH_MAVEN_PKG_USER }}

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B --no-transfer-progress deploy -DskipTests -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
