# This workflow will build a package using Maven and publish it to GitHub Packages. It will also create a new release.

name: Publish Maven packages and create release

on:
  workflow_dispatch:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - run: mvn -B install --no-transfer-progress -s .mvn-ci.xml --file pom.xml

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github
        settings-path: ${{ github.workspace }}
        
    - name: Get version
      run: echo project_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) | sed -r 's/-SNAPSHOT//' >> $GITHUB_ENV

    - name: Set project version
      run: mvn versions:set "-DnewVersion=${{ env.project_version }}"

    - name: Build with Maven
      run: mvn -B package -s .mvn-ci.xml --file pom.xml
      env:
        GH_MAVEN_PKG_AUTH_TOKEN: ${{ secrets.GH_MAVEN_PKG_AUTH_TOKEN }}
        GH_MAVEN_PKG_USER: ${{ secrets.GH_MAVEN_PKG_USER }}

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B --no-transfer-progress deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Create release
      uses: "softprops/action-gh-release@v1"
      with:
        tag_name: v${{ env.project_version }}
        prerelease: false
        name: v${{ env.project_version }}
        generate_release_notes: true
        fail_on_unmatched_files: true
        body: |
          Maven Dependency:
          ```
          <dependencies>
            <dependency>
                <groupId>care.smith.top</groupId>
                <artifactId>top-phenotypic-query</artifactId>
                <version>${{ env.project_version }}</version>
            </dependency>
          </dependencies>
          ```
        files: |
          LICENSE
          target/*.jar
